apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
spec:
  destination:
    name: ''
    server: 'https://kubernetes.default.svc'
    namespace: default
  source:
    path: apps
    repoURL: https://github.com/maurex-dev/argotest.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  