apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-helm-nginx
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/maurex-dev/argotest.git'
    targetRevision: HEAD
  project: default