apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-helm-nginx
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://maurex-dev.github.io/helm-nginx'
    targetRevision: ''
    chart: helm-nginx
  sources: []
  project: default

